context:
  version: "2.11.4"

package:
  name: faad2
  version: ${{ version }}

source:
  url: https://github.com/knik0/faad2/archive//${{ version }}.tar.gz
  sha256: ee479ccbae4a8387ab696e6f21a481bd83fe3881471cafa81b4ae59d7d3aed43

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  run_exports:
    - ${{ pin_subpackage('faad2') }}

tests:
  - script:
      - faad -h 2>&1 | grep -q "Ahead Software MPEG-4 AAC Decoder"

about:
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: ISO AAC audio decoder
  homepage: https://sourceforge.net/projects/faac
  repository: https://github.com/knik0/faad2

extra:
  recipe-maintainers:
    - danielnachun
