context:
  version: "2.11.2"

package:
  name: faad2
  version: ${{ version }}

source:
  url: https://github.com/knik0/faad2/archive//${{ version }}.tar.gz
  sha256: 3fcbd305e4abd34768c62050e18ca0986f7d9c5eca343fb98275418013065c0e

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  run_exports:
    - ${{ pin_subpackage('faad2') }}

tests:
  - script:
      - faad -h 2>&1 | grep -q "Ahead Software MPEG-4 AAC Decoder"


about:
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: ISO AAC audio decoder
  homepage: https://sourceforge.net/projects/faac
  repository: https://github.com/knik0/faad2

extra:
  recipe-maintainers:
    - danielnachun
