context:
  version: "2.11.3"

package:
  name: faad2
  version: ${{ version }}

source:
  url: https://github.com/knik0/faad2/archive//${{ version }}.tar.gz
  sha256: 860ab62087e336c1844a70e33196c1790b525fb9a9e7b6ac4fab1a1a4e4d5ce8

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  run_exports:
    - ${{ pin_subpackage('faad2') }}

tests:
  - script:
      - faad -h 2>&1 | grep -q "Ahead Software MPEG-4 AAC Decoder"

about:
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: ISO AAC audio decoder
  homepage: https://sourceforge.net/projects/faac
  repository: https://github.com/knik0/faad2

extra:
  recipe-maintainers:
    - danielnachun
